name: Build Ubicloud Image
run-name: ${{ inputs.input_name }} - ${{ inputs.output_name }}
# GitHub Action port from Azure Pipelines version
# https://github.com/actions/runner-images/blob/main/images.CI/linux-and-win/azure-pipelines/image-generation.yml

on:
  workflow_dispatch:
    inputs:
      input_name:
        required: true
        type: string
      output_name:
        required: true
        type: string
      prod_account:
        description: "Upload images to prod account"
        required: true
        default: true
        type: boolean
      dev_account:
        description: "Upload images to dev account"
        required: true
        default: true
        type: boolean

concurrency: "${{ inputs.input_name }}-${{ inputs.output_name }}"

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    name: upload ${{ inputs.input_name }}
    runs-on: ubicloud-standard-16
    env:
      MC_HOST_ubicloud: ${{ secrets.MINIO_CONNECTION_STRING }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install MinIO client
        run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc -o mc
          sudo mv mc /usr/bin/mc
          sudo chmod +x /usr/bin/mc
          mc --version

      - name: Set MinIO root certificates
        run: |
          mkdir -p ~/.mc/certs/CAs
          cat <<EOT > ~/.mc/certs/CAs/ubicloud_images_blob_storage_certs.crt
          ${{ secrets.MINIO_ROOT_CERTIFICATES }}
          EOT
      
      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Download the RAW image from MinIO
        run: |
          mc cp ubicloud/ubicloud-images/${{ inputs.input_name }} ${{ inputs.input_name }}
          mc cp ubicloud/ubicloud-images/${{ inputs.input_name }}.sha256 ${{ inputs.input_name }}.sha256

      - name: Rename the image
        if: ${{ inputs.input_name != inputs.output_name }}
        run: |
          mv ${{ inputs.input_name }} ${{ inputs.output_name }}
          mv ${{ inputs.input_name }}.sha256 ${{ inputs.output_name }}.sha256
      - name: Upload image to R2 dev account
        if: ${{ inputs.dev_account }}
        run: |
          rclone config create r2-dev s3 \
            provider Cloudflare \
            access_key_id ${{secrets.CLOUDFLARE_R2_DEV_ACCESS_KEY_ID }} \
            secret_access_key ${{secrets.CLOUDFLARE_R2_DEV_SECRET_ACCESS_KEY }} \
            endpoint ${{secrets.CLOUDFLARE_R2_DEV_ENDPOINT }} \
            no_check_bucket true

          rclone copy ${{ inputs.output_name }} r2-dev:ubicloud-images-dev/
          rclone copy ${{ inputs.output_name }}.sha256 r2-dev:ubicloud-images-dev/

      - name: Upload image to R2 prod account
        if: ${{ inputs.prod_account }}
        run: |
          rclone config create r2-prod s3 \
            provider Cloudflare \
            access_key_id ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }} \
            secret_access_key ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }} \
            endpoint ${{ secrets.CLOUDFLARE_R2_ENDPOINT }} \
            no_check_bucket true

          rclone copy ${{ inputs.output_name }} r2-prod:ubicloud-images/
          rclone copy ${{ inputs.output_name }}.sha256 r2-prod:ubicloud-images/
